version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - default
    deploy:
      replicas: 1

  minio1:
    image: minio/minio
    hostname: minio1
    command: server /data{1...4}  # Use 4 data directories
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data1:/data1
      - minio_data2:/data2
      - minio_data3:/data3
      - minio_data4:/data4
    networks:
      - default
    deploy:
      placement:
        constraints:
          - node.role == manager

  object-receiver:
    image: localhost:5000/object-receiver:latest
    ports:
      - "8000:8000"
    networks:
      - default
    deploy:
      replicas: 5
    depends_on:
      - rabbitmq
      - minio1

  object-getter:
    image: localhost:5000/object-getter:latest
    ports:
      - "8001:8000"
    networks:
      - default
    deploy:
      replicas: 3
    depends_on:
      - rabbitmq
      - minio1

  orchestrator:
    image: localhost:5000/orchestrator:latest
    ports:
      - "8002:8000"
    networks:
      - default
    deploy:
      replicas: 1
    depends_on:
      - rabbitmq

volumes:
  minio_data1:
  minio_data2:
  minio_data3:
  minio_data4:

networks:
  default:
    driver: overlay
