version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      replicas: 1

  minio:
    image: minio/minio
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    deploy:
      replicas: 1

  object-receiver:
    image: localhost:5000/object-receiver:latest
    ports:
      - "8000:8000"
    deploy:
      replicas: 3
    depends_on:
      - rabbitmq
      - minio

  object-getter:
    image: localhost:5000/object-getter:latest
    ports:
      - "8001:8000"
    deploy:
      replicas: 3
    depends_on:
      - rabbitmq
      - minio

  orchestrator:
    image: localhost:5000/orchestrator:latest
    ports:
      - "8002:8000"
    deploy:
      replicas: 1
    depends_on:
      - rabbitmq

volumes:
  minio_data:

networks:
  default:
    driver: overlay
